[logger]
level = "INFO"
type = "FILE"
directory = "logs"

[storage]
type = "db"
user = "svend"
pass = "p@ssw0rd"
port = 5431
host = "127.0.0.1"
name = "db_calendar"

[server]
host = "127.0.0.1"
port = "8080"
